# Generated by Django 4.1.3 on 2023-01-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_merge_20230119_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='TestProxy',
        ),
    ]
