# Generated by Django 2.0.4 on 2023-01-31 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stock_id_delete_testproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProxy',
            fields=[
                ('stock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.stock')),
            ],
            bases=('stock.stock',),
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '在庫', 'verbose_name_plural': '在庫'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
