# Generated by Django 4.1.2 on 2022-11-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_count", models.IntegerField(verbose_name="利用者人数")),
                ("table_number", models.IntegerField(verbose_name="テーブル番号")),
            ],
        ),
    ]
