# Generated by Django 4.1.2 on 2022-11-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="menu_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="メニュー名")),
                ("count", models.IntegerField(verbose_name="価格")),
            ],
        ),
    ]
