# Generated by Django 4.1.3 on 2023-01-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_options'),
        ('stock', '0003_auto_20221222_1128'),
    ]

    operations = [
    ]
