# Generated by Django 4.1.2 on 2022-12-06 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Home_Folder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrurl",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="qrurl",
            name="tableNumber",
            field=models.PositiveSmallIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
