# Generated by Django 2.0.4 on 2022-12-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'アカウント', 'verbose_name_plural': 'アカウント'},
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
